name: interactive_cv
description: Project of my interactive web CV
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.0
  firebase_crashlytics: ^3.0.3
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.0.15
  sprintf: ^7.0.0
  uuid: ^3.0.6

dev_dependencies:
  assets_gen: ^1.2.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #